#ifndef SLOPE_H
#define SLOPE_H

#include "content/config/Options.h"
#include "content/screen_primitives/media/Image.h"
#include "content/screen_primitives/media/Video.h"
#include "content/screen_primitives/media/Webcam.h"
#include "content/screen_primitives/text/Text.h"
#include "math/kernels.h"
#include "slides/core/Slideshow.h"
#include "slides/deck/DeckLoader.h"
#include "content/polyscope_primitives/PointCloud.h"
#include "content/screen_primitives/text/LateX.h"
#include "content/polyscope_primitives/Mesh.h"
#include "content/scripting/Snippet.h"
#include "content/polyscope_primitives/PolyscopeSnippets.h"
#include "content/polyscope_primitives/quantities/MeshScalarField.h"
#include "content/polyscope_primitives/quantities/vector_field.h"
#include "content/polyscope_primitives/Curve3D.h"
#include "content/polyscope_primitives/Point.h"
#include "content/config/io.h"
#include "content/polyscope_primitives/CameraView.h"
#include "content/screen_primitives/widgets/ImGuiWidgets.h"
#include "slides/ui/Panel.h"
#include "content/polyscope_primitives/BackgroundColor.h"
#include "content/polyscope_primitives/VolumeGrid.h"
#include "content/screen_primitives/shapes/Box.h"
#include "content/screen_primitives/shapes/Shape2D.h"
#include "content/screen_primitives/shapes/Stack2D.h"
#include "content/screen_primitives/gpu/Shader.h"
#include "content/config/Params.h"

#endif // SLOPE_H
